version: '3.9'
services:
  client:
    image: .
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server
  server:
    image: .
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
