version: '1.0'
services:
  client:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/client
    depends_on:
      - 'server'

  server:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - .:/server
